### ISSUE TITLE
Auth Page Needed

### ISSUE THREAD

**Issue by yashweblife** [codespirityash/express-todo-app#5]
Can you add an `auth.html` page to the project with login and signup boxes
this css prop basically hides anything
```css
.display-off {
    display:none !important;
}
```

and in js

```javascript
function toggleAuthForm(){
    loginForm.classList.toggle("display-off");
    signupForm.classList.toggle("display-off");
}
signupInsteadButton.addEventListener("click", toggleAuthForm)
loginInsteadButton.addEventListener("click", toggleAuthForm)
```
